# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/gabeg/Unreal Engine/UE_5.7

TARGETS = \
	StrategyGame-Android-DebugGame  \
	StrategyGame-Android-Development  \
	StrategyGame-Android-Shipping  \
	StrategyGame-Linux-DebugGame  \
	StrategyGame-Linux-Development  \
	StrategyGame-Linux-Shipping  \
	StrategyGame-LinuxArm64-DebugGame  \
	StrategyGame-LinuxArm64-Development  \
	StrategyGame-LinuxArm64-Shipping  \
	StrategyGame \
	StrategyGameEditor-Linux-DebugGame  \
	StrategyGameEditor-Linux-Development  \
	StrategyGameEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend StrategyGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug StrategyGameEditor-Linux-Debug


StrategyGame-Android-DebugGame:
	 $(BUILD) StrategyGame Android DebugGame  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-Android-Development:
	 $(BUILD) StrategyGame Android Development  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-Android-Shipping:
	 $(BUILD) StrategyGame Android Shipping  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-Linux-DebugGame:
	 $(BUILD) StrategyGame Linux DebugGame  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-Linux-Development:
	 $(BUILD) StrategyGame Linux Development  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-Linux-Shipping:
	 $(BUILD) StrategyGame Linux Shipping  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-LinuxArm64-DebugGame:
	 $(BUILD) StrategyGame LinuxArm64 DebugGame  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-LinuxArm64-Development:
	 $(BUILD) StrategyGame LinuxArm64 Development  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame-LinuxArm64-Shipping:
	 $(BUILD) StrategyGame LinuxArm64 Shipping  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGame: StrategyGame-Linux-Development

StrategyGameEditor-Linux-DebugGame:
	 $(BUILD) StrategyGameEditor Linux DebugGame  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGameEditor-Linux-Development:
	 $(BUILD) StrategyGameEditor Linux Development  -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" $(ARGS)

StrategyGameEditor: StrategyGameEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/gabeg/Documents/Unreal Projects/StrategyGame/StrategyGame.uproject" -Game 

.PHONY: $(TARGETS)
